IF OBJECT_ID('app.Users', 'U') IS NULL
BEGIN
    CREATE TABLE app.Users
    (
        UserId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Users PRIMARY KEY,
        Username NVARCHAR(255) NOT NULL CONSTRAINT UQ_Users_Username UNIQUE,
        Email NVARCHAR(255) NOT NULL CONSTRAINT UQ_Users_Email UNIQUE,
        AzureADObjectId NVARCHAR(100) NULL,
        DisplayName NVARCHAR(255) NULL,
        IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
        CreateDate DATETIME2 NOT NULL CONSTRAINT DF_Users_CreateDate DEFAULT (SYSUTCDATETIME()),
        CreatedBy NVARCHAR(255) NOT NULL CONSTRAINT DF_Users_CreatedBy DEFAULT (SUSER_SNAME()),
        UpdateDate DATETIME2 NOT NULL CONSTRAINT DF_Users_UpdateDate DEFAULT (SYSUTCDATETIME()),
        UpdatedBy NVARCHAR(255) NOT NULL CONSTRAINT DF_Users_UpdatedBy DEFAULT (SUSER_SNAME())
    );
END;
